### ISSUE TITLE
نوشتن بهتر مهارت‌ها

### ISSUE THREAD

**Issue by ekm507** [mertz1999/mertz1999#1]
سلام! این صفحه اولی که گذاشته‌ای قشنگ شده.

به نظرم بهتره مهارت‌هایت رو کامل‌تر بنویسی.

-  FPGA Developer based Xilinx Processors
-  Signal processing (like: Image, Audio)
-  Deep learning and Computer vision
-  Machine Learning and Data Analytics

اینطوری:
    ~Signal processing (like: Image, Audio)~
    Signal processing 
+ Image processing specialist
+ Audio processing

~FPGA Developer based Xilinx Processors~

FPGA Developer
+ specialist in Xilinx Spartan series
+ microprocessor design
+ signal processing on fpga
+ designing image processing systems on FPGA

بقیه هم مثل همین.

**Comment by mertz1999** [comment]
صحیح. خیلی ممنونم که اینقدر دقت کردی.
حتما انجامش میدم.
